
bootloader:
	printf "Building:\tbootloader\n"
	$(ASM) $(ASM_FLAGS) bootloader/source/stage1.asm -o $(BUILD_DIR)/bootloader/stage1.o
	$(ASM) $(ASM_FLAGS) bootloader/source/stage2.asm -o $(BUILD_DIR)/bootloader/stage2.o
